
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rabbitctf_frontend
    ports:
      - "8080:80"       # host:container
    depends_on:
      - backend
    networks:
      - rabbitctf_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rabbitctf_backend
    environment:
      DATABASE_URL: postgresql+psycopg://rabbitctf:rabbitctf@db:5432/rabbitctf
    depends_on:
      - db
    volumes:
      - backend_uploads:/app/uploads  # persistent uploads
    networks:
      - rabbitctf_network

  db:
    image: postgres:18-alpine
    container_name: rabbitctf_db
    environment:
      POSTGRES_DB: rabbitctf
      POSTGRES_USER: rabbitctf
      POSTGRES_PASSWORD: rabbitctf
    volumes:
      - postgres_data:/var/lib/postgresql/data  # persistent database data
      - ./backend/db/init:/docker-entrypoint-initdb.d:ro  # initialization scripts - read-only
    networks:
      - rabbitctf_network

volumes:
  postgres_data:
    name: rabbitctf_postgres_data
  backend_uploads:
    name: rabbitctf_backend_uploads
networks:
  rabbitctf_network:
    driver: bridge